#ifndef INDIRECT_COMP
#define INDIRECT_COMP

#define DISPATCH_INDIRECT_UPDATE_PARTICLES 0
#define DISPATCH_INDIRECT_BROAD_PHASE_COLLISION_DETECTION 1
#define DISPATCH_INDIRECT_BROAD_PHASE_COLLISION_DETECTION_CLEANUP 2
#define DISPATCH_INDIRECT_SOLVE_CONSTRAINTS 3
#define DISPATCH_INDIRECT_UPDATE_BONES 4
#define DISPATCH_INDIRECT_AGENT_SENSORY_INPUT_UPDATE 5
#define DISPATCH_INDIRECT_FEED_FORWARD_NET 6
#define DISPATCH_INDIRECT_LEN 7
#define DRAW_INDIRECT_BONES 0
#define DRAW_INDIRECT_BLOCK 1
#define DRAW_INDIRECT_PARTICLES 2
#define DRAW_INDIRECT_LEN 3
struct DispatchIndirectCommand{
    uint    x;
    uint    y;
    uint    z;
};
struct DrawIndirectCommand{
    uint vertex_count;
    uint instance_count;
    uint first_vertex;
    uint first_instance;
};
#endif